# Generated by Django 3.2 on 2021-10-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('deposit_amount', models.IntegerField(default=0)),
                ('amount_sold', models.IntegerField(default=0)),
                ('billing_price', models.IntegerField()),
                ('total', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('SELESAI', 'SELESAI'), ('BELUM SELESAI', 'BELUM SELESAI')], default='BELUM SELESAI', max_length=20)),
            ],
        ),
    ]
