# Generated by Django 3.2 on 2021-09-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biotoko',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='biotoko',
            name='picture',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
