# Generated by Django 3.2 on 2021-09-29 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warung', '0002_auto_20210929_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biotoko',
            name='picture',
        ),
    ]
