# Generated by Django 3.2 on 2021-09-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warung', '0003_remove_biotoko_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Stocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('qty', models.IntegerField()),
                ('purchase_price', models.IntegerField()),
                ('billing_prince', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('billing_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warung.category')),
                ('stocker_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warung.stocker')),
            ],
        ),
    ]
