# Generated by Django 3.2 on 2021-10-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warung', '0004_category_goods_stocker'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='purchase_perqty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
