# Generated by Django 3.2 on 2021-10-02 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warung', '0005_goods_purchase_perqty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='billing_date',
        ),
    ]
