# Generated by Django 3.2 on 2021-10-02 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warung', '0007_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('qty', models.IntegerField()),
                ('total_sold', models.IntegerField()),
                ('name_sold', models.ForeignKey(max_length=70, on_delete=django.db.models.deletion.CASCADE, to='warung.goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('qty', models.IntegerField()),
                ('note', models.TextField(blank=True)),
                ('total_debt', models.IntegerField()),
                ('name_debt', models.ForeignKey(max_length=70, on_delete=django.db.models.deletion.CASCADE, to='warung.goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
