# Generated by Django 3.2 on 2021-10-06 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warung', '0008_debt_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='item_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataku', to='warung.category'),
        ),
    ]
