# Generated by Django 3.2 on 2021-10-06 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warung', '0009_auto_20211006_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('qty', models.IntegerField(default=0)),
                ('purchase_price', models.IntegerField()),
                ('purchase_perqty', models.IntegerField()),
                ('billing_prince', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('item_sold', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataku', to='warung.category')),
                ('stocker_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warung.stocker')),
            ],
        ),
        migrations.RemoveField(
            model_name='goods',
            name='category',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='stocker_name',
        ),
        migrations.DeleteModel(
            name='Sold',
        ),
        migrations.AlterField(
            model_name='debt',
            name='name_debt',
            field=models.ForeignKey(max_length=70, on_delete=django.db.models.deletion.CASCADE, to='warung.good'),
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
