# Generated by Django 3.2 on 2021-10-18 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocker', '0001_initial'),
        ('warung', '0010_auto_20211006_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='stocker_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocker.stocker'),
        ),
        migrations.DeleteModel(
            name='Stocker',
        ),
    ]
