# Generated by Django 3.2 on 2021-10-18 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warung', '0011_auto_20211018_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
