# Generated by Django 3.2 on 2021-10-18 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warung', '0012_delete_deposit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Debt',
        ),
    ]
